version: '3'

services:
  app:
    container_name: fast-message
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    build:
      context: ./
      dockerfile: ./docker/fastmessage/Dockerfile
    ports:
      - "6968:8080"
#    networks:
#      fastmessagenet:
#        ipv4_address: 69.69.0.5
    depends_on:
      - fast-message-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fast-message-db:5432/fastmessage
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  fast-message-db:
    image: 'postgres:latest'
    container_name: fast-message-db
    ports:
      - "5432:5432"
#    networks:
#      fastmessagenet:
#        ipv4_address: 69.69.0.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastmessage

#networks:
#  fastmessagenet:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 69.69.0.0/16